[project]
name = "3d-cad-designer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.9"

dependencies = ["easier-openai", "beautifulsoup4", "scikit-learn", "joblib", "numpy", "pyperclip"]
